# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 452e35ee25de7efbfa3a835c072dcb0258b9ab98648d8f6be37d71ea5c59872387c8273ced82a0ad43bcbd6ec6f3b89394a5725fc51263d56994ccc683e7eaad

test:
  secret_key_base: 16d509ad497688b9a88d4b720de60fa13e0d591fa674ad77495bd20ac63996add9605c22c8c9e819ee02c2a1b13911213df2c08218797f49d59a04cf6be73915

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
